# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(940, 527)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ffmpegfolder_lineEdit = QtWidgets.QLineEdit(Form)
        self.ffmpegfolder_lineEdit.setObjectName("ffmpegfolder_lineEdit")
        self.gridLayout.addWidget(self.ffmpegfolder_lineEdit, 0, 1, 1, 1)
        self.ffmpegfolder_Button = QtWidgets.QPushButton(Form)
        self.ffmpegfolder_Button.setObjectName("ffmpegfolder_Button")
        self.gridLayout.addWidget(self.ffmpegfolder_Button, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.workspace_lineEdit = QtWidgets.QLineEdit(Form)
        self.workspace_lineEdit.setObjectName("workspace_lineEdit")
        self.gridLayout.addWidget(self.workspace_lineEdit, 1, 1, 1, 1)
        self.workspace_Button = QtWidgets.QPushButton(Form)
        self.workspace_Button.setObjectName("workspace_Button")
        self.gridLayout.addWidget(self.workspace_Button, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.filenames_lineEdit = QtWidgets.QLineEdit(Form)
        self.filenames_lineEdit.setObjectName("filenames_lineEdit")
        self.gridLayout.addWidget(self.filenames_lineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.input_fps_lineEdit = QtWidgets.QLineEdit(Form)
        self.input_fps_lineEdit.setObjectName("input_fps_lineEdit")
        self.gridLayout.addWidget(self.input_fps_lineEdit, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.output_fps_lineEdit = QtWidgets.QLineEdit(Form)
        self.output_fps_lineEdit.setObjectName("output_fps_lineEdit")
        self.gridLayout.addWidget(self.output_fps_lineEdit, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.quality_Slider = QtWidgets.QSlider(Form)
        self.quality_Slider.setMinimum(18)
        self.quality_Slider.setMaximum(26)
        self.quality_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.quality_Slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.quality_Slider.setObjectName("quality_Slider")
        self.gridLayout.addWidget(self.quality_Slider, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_Button = QtWidgets.QPushButton(Form)
        self.check_Button.setObjectName("check_Button")
        self.horizontalLayout.addWidget(self.check_Button)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.convert_Button = QtWidgets.QPushButton(Form)
        self.convert_Button.setObjectName("convert_Button")
        self.horizontalLayout.addWidget(self.convert_Button)
        self.play_Button = QtWidgets.QPushButton(Form)
        self.play_Button.setObjectName("play_Button")
        self.horizontalLayout.addWidget(self.play_Button)
        self.probe_Button = QtWidgets.QPushButton(Form)
        self.probe_Button.setObjectName("probe_Button")
        self.horizontalLayout.addWidget(self.probe_Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img_Label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_Label.sizePolicy().hasHeightForWidth())
        self.img_Label.setSizePolicy(sizePolicy)
        self.img_Label.setMinimumSize(QtCore.QSize(500, 0))
        self.img_Label.setMaximumSize(QtCore.QSize(500, 16777215))
        self.img_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.img_Label.setObjectName("img_Label")
        self.verticalLayout_2.addWidget(self.img_Label)
        self.img_Slider = QtWidgets.QSlider(Form)
        self.img_Slider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.img_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.img_Slider.setObjectName("img_Slider")
        self.verticalLayout_2.addWidget(self.img_Slider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ffmpeg folder"))
        self.ffmpegfolder_lineEdit.setText(_translate("Form", "/usr/bin"))
        self.ffmpegfolder_Button.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "workspace"))
        self.workspace_lineEdit.setText(_translate("Form", "/home/boman/Downloads/workspace/apps_ale_coining3D"))
        self.workspace_Button.setText(_translate("Form", "..."))
        self.label_3.setText(_translate("Form", "filenames"))
        self.filenames_lineEdit.setText(_translate("Form", "anim%4d.bmp"))
        self.label_4.setText(_translate("Form", "input fps"))
        self.input_fps_lineEdit.setText(_translate("Form", "10"))
        self.label_5.setText(_translate("Form", "output fps"))
        self.output_fps_lineEdit.setText(_translate("Form", "25"))
        self.label_6.setText(_translate("Form", "quality"))
        self.check_Button.setText(_translate("Form", "Check"))
        self.convert_Button.setText(_translate("Form", "Convert"))
        self.play_Button.setText(_translate("Form", "Play"))
        self.probe_Button.setText(_translate("Form", "Probe"))
        self.img_Label.setText(_translate("Form", "IMAGE"))

