# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(593, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ffmpegfolder_lineEdit = QtWidgets.QLineEdit(Form)
        self.ffmpegfolder_lineEdit.setObjectName("ffmpegfolder_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ffmpegfolder_lineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.workspace_lineEdit = QtWidgets.QLineEdit(Form)
        self.workspace_lineEdit.setObjectName("workspace_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.workspace_lineEdit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.filenames_lineEdit = QtWidgets.QLineEdit(Form)
        self.filenames_lineEdit.setObjectName("filenames_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filenames_lineEdit)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_fps_lineEdit = QtWidgets.QLineEdit(Form)
        self.input_fps_lineEdit.setObjectName("input_fps_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_fps_lineEdit)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.output_fps_lineEdit = QtWidgets.QLineEdit(Form)
        self.output_fps_lineEdit.setObjectName("output_fps_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.output_fps_lineEdit)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.quality_Slider = QtWidgets.QSlider(Form)
        self.quality_Slider.setMinimum(18)
        self.quality_Slider.setMaximum(26)
        self.quality_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.quality_Slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.quality_Slider.setObjectName("quality_Slider")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.quality_Slider)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.convert_Button = QtWidgets.QPushButton(Form)
        self.convert_Button.setObjectName("convert_Button")
        self.horizontalLayout.addWidget(self.convert_Button)
        self.play_Button = QtWidgets.QPushButton(Form)
        self.play_Button.setObjectName("play_Button")
        self.horizontalLayout.addWidget(self.play_Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ffmpeg folder"))
        self.ffmpegfolder_lineEdit.setText(_translate("Form", "/usr/bin"))
        self.label_2.setText(_translate("Form", "workspace"))
        self.workspace_lineEdit.setText(_translate("Form", "/home/boman/Downloads/workspace/apps_ale_coining3D"))
        self.label_3.setText(_translate("Form", "filenames"))
        self.filenames_lineEdit.setText(_translate("Form", "anim%4d.bmp"))
        self.label_4.setText(_translate("Form", "input fps"))
        self.input_fps_lineEdit.setText(_translate("Form", "10"))
        self.label_5.setText(_translate("Form", "output fps"))
        self.output_fps_lineEdit.setText(_translate("Form", "25"))
        self.label_6.setText(_translate("Form", "quality"))
        self.convert_Button.setText(_translate("Form", "Convert"))
        self.play_Button.setText(_translate("Form", "Play"))

