
dist: trusty
sudo: false
language: cpp
sudo: required

#addons:
#  apt:
#    packages:
      #- cmake    # inutile
      #- doxygen
      #- graphviz
      #- python-pip



before_install:
  - export PROG_BASE_DIR=$(pwd)
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update #-qq

install: 
  # C++14
  - sudo apt-get install g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # swig
  - sudo apt-get install swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  # numpy
  - sudo apt-get install python-numpy  
  # gmm
  - sudo apt-get install libgmm++-dev

script:
  - cd ${PROG_BASE_DIR}/apps/EHD  && ./travis.sh
  - cd ${PROG_BASE_DIR}/apps/fractal/cpp  && ./travis.sh
  - cd ${PROG_BASE_DIR}/apps/GenMAI  && ./travis.sh
  - cd ${PROG_BASE_DIR}/apps/md5  && ./travis.sh
  - cd ${PROG_BASE_DIR}/apps/minibarreTE  && ./travis.sh
  #- cd ${PROG_BASE_DIR}/student/dcm1  && ./travis.sh    # requires Qt
  - cd ${PROG_BASE_DIR}/student/dcm2  && ./travis.sh
