#include "FC.h"         // generated by CMake
#include "f_routines.h" // missing prototypes

#include <iostream>

/// C routine which can be called from FORTRAN
extern "C" void FC_GLOBAL(croutine, CROUTINE)(int *i, double *d)
{
    std::cout << "in croutine()\n";
    std::cout << "d = " << *d << "   i = " << *i << "\n";
    FC_GLOBAL(froutine, FROUTINE)();
    std::cout << "back to C++\n";
}
