dist: bionic
sudo: false
language: cpp
sudo: required

# addons:
#  apt:
#    packages:
#       - cmake    # inutile
#       - doxygen
#       - graphviz
#       - python-pip

before_install:
  - export PROG_BASE_DIR=$(pwd)

install: 
  # fortran
  - sudo apt install gfortran
  # swig
  - sudo apt-get install swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  # numpy
  - sudo apt-get install python3-numpy  
  # gmm
  - sudo apt-get install libgmm++-dev

script:
  - cd ${PROG_BASE_DIR}  && python3 ./build_all.py --travis
