#include "FC.h"  // generated by CMake

#include <iostream>

extern "C"
{
    void FC_GLOBAL(froutine, FROUTINE)();
}

/// C routine which can be called from FORTRAN
extern "C"
void FC_GLOBAL(croutine, CROUTINE)()
{
    std::cout << "in croutine()\n";
    FC_GLOBAL(froutine, FROUTINE)();
    std::cout << "back to C++\n";
}

