# FindTBB.cmake - try to find TBB libs


OPTION(TBB_USE_TBBMALLOC "Use TBBMALLOC" ON)

MESSAGE(STATUS "-------------------------------------")
MESSAGE(STATUS " FindTBB")
MESSAGE(STATUS "-------------------------------------")

#MESSAGE(STATUS "CMAKE_SHARED_LIBRARY_SUFFIX=${CMAKE_SHARED_LIBRARY_SUFFIX}")
#MESSAGE(STATUS "CMAKE_SHARED_MODULE_SUFFIX=${CMAKE_SHARED_MODULE_SUFFIX}")
#MESSAGE(STATUS "CMAKE_FIND_LIBRARY_SUFFIX=${CMAKE_FIND_LIBRARY_SUFFIX}")
#MESSAGE(STATUS "TBB_FIND_REQUIRED=${TBB_FIND_REQUIRED}") # automatiquement à 1 si REQUIRED
#MESSAGE(STATUS "TBB_USE_TBBMALLOC=${TBB_USE_TBBMALLOC}")
#MESSAGE(STATUS "WIN32=${WIN32}")
#MESSAGE(STATUS "MSVC=${MSVC}")
#MESSAGE(STATUS "MINGW=${MINGW}")

# --- Liste des bibliothèques à trouver ---
# --- TBB_LIBS/TBB_LIBS_DEBUG ---

SET(TBB_LIBS       tbb)
SET(TBB_LIBS_DEBUG tbb_debug)

IF(TBB_USE_TBBMALLOC)
	SET(TBB_LIBS       ${TBB_LIBS}       tbbmalloc_proxy       tbbmalloc)
	SET(TBB_LIBS_DEBUG ${TBB_LIBS_DEBUG} tbbmalloc_proxy_debug tbbmalloc_debug)
ENDIF(TBB_USE_TBBMALLOC)

MESSAGE(STATUS "TBB_LIBS=${TBB_LIBS}")
MESSAGE(STATUS "TBB_LIBS_DEBUG=${TBB_LIBS_DEBUG}")

# -- try to guess TBBROOT from the PATH -- 

# try to find "tbb.dll/so" in the PATH
find_library(FOUND_LIB "tbb" PATHS "")
MESSAGE(STATUS "FOUND_LIB=${FOUND_LIB}")

SET(TBB_CANDIDATE_DIR "")
WHILE("${TBB_CANDIDATE_DIR}" STREQUAL "")
	get_filename_component(DIRNAME ${FOUND_LIB} PATH)
	#MESSAGE(STATUS "DIRNAME=${DIRNAME}")	
	get_filename_component(BASENAME ${FOUND_LIB} NAME)
	#MESSAGE(STATUS "BASENAME=${BASENAME}") # on remonte jusqu'à un "lib" ou "build"

	IF("${BASENAME}" STREQUAL "")
		SET(TBB_CANDIDATE_DIR "NOT-FOUND")
	ENDIF()
	
	IF( ("${BASENAME}" STREQUAL "lib") OR ("${BASENAME}" STREQUAL "build") )
		SET(TBB_CANDIDATE_DIR ${DIRNAME})
	ELSE()
		SET(FOUND_LIB ${DIRNAME})
		#MESSAGE(STATUS "FOUND_LIB=${FOUND_LIB}")
	ENDIF()
ENDWHILE()

MESSAGE(STATUS "TBB_CANDIDATE_DIR=${TBB_CANDIDATE_DIR}")
MESSAGE(STATUS "TBBROOT=$ENV{TBBROOT}")



# --- TBB_INCLUDE_PATH ---

SET(TBB_INCLUDE_PATH TBB_INCLUDE_PATH-NOTFOUND CACHE PATH "" FORCE) # enlever le "FORCE" par la suite
FIND_PATH(TBB_INCLUDE_PATH 
             NAMES  tbb/parallel_for.h
			 PATHS "${TBB_CANDIDATE_DIR}"
			 PATH_SUFFIXES include
            )
MESSAGE(STATUS "TBB_INCLUDE_PATH=${TBB_INCLUDE_PATH}")

#$ENV{TBBROOT}/include;


# --- TBB_LIB_PATH ---

SET(TBB_LIB_PATH TBB_LIB_PATH-NOTFOUND CACHE PATH "" FORCE)
MESSAGE(STATUS "TBB_LIB_PATH=${TBB_LIB_PATH}")		

SET(TBB_LIB_PATH_DESC "directory containing ${TBB_LIBS}")
SET(TBB_LIB_PATH_MESG "Set the TBB_LIB_PATH cmake cache entry to the ${TBB_LIB_PATH_DESC}")
FIND_PATH(TBB_LIB_PATH 
             NAMES tbb
			 PATHS "${TBB_LIBS}"
             DOC "The ${TBB_LIB_PATH_MESG}"
            )
MESSAGE(STATUS "TBB_LIB_PATH=${TBB_LIB_PATH}")		

IF(NOT TBB_LIB_PATH)
    MESSAGE(FATAL_ERROR "${TBB_LIB_PATH_MESG}")
ENDIF(NOT TBB_LIB_PATH)

# --- TBB_DEBUG_LIB_PATH ---

SET(TBB_DEBUG_LIB_PATH TBB_DEBUG_LIB_PATH-NOTFOUND CACHE PATH "")

SET(TBB_DEBUG_LIB_PATH_DESC "directory containing tbb_debug.lib")
SET(TBB_DEBUG_LIB_PATH_MESG "Set the TBB_DEBUG_LIB_PATH cmake cache entry to the ${TBB_DEBUG_LIB_PATH_DESC}")
FIND_PATH(TBB_DEBUG_LIB_PATH
             NAMES tbb_debug.lib tbb_debug
             DOC "The ${TBB_DEBUG_LIB_PATH_MESG}"
            )
IF(NOT TBB_DEBUG_LIB_PATH)
    MESSAGE(FATAL_ERROR ${TBB_DEBUG_LIB_PATH_MESG})
ENDIF(NOT TBB_DEBUG_LIB_PATH)


